live_config_reload = true

import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "full"
dynamic_padding = false
decorations_theme_variant = "dark"
# opacity = 0.9

[window.padding]
# top = 50
# x = 25
# y = 20

[font]
size = 14.0

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"
